### ISSUE TITLE
Issues installing on M1 Mac

### ISSUE THREAD

**Issue by anaklim** [sisinflab/elliot#20]
Please let me know if this has been already discussed before - I've tried finding any information and failed.
I have attempted to install Elliot according to the instructions in the docs:
```
git clone https://github.com//sisinflab/elliot.git && cd elliot
virtualenv -p /usr/bin/pyhton3.6 venv # your python location and version
source venv/bin/activate
pip install --upgrade pip
pip install -e . --verbose
```

I am using a MacBook Pro with M1 Pro chip, 12.0.1 Monterey OS, Python version 3.9 installed with Homebrew. 
It looks like there is some issue with Cython and some installation quirk, but I really don't know how to approach solving this. Please let me know if anyone else had such an issue previously.

When I run the last pip install command I get the following terminal output:

```
Using pip 22.0.4 from /Users/anastasiia/Desktop/elliot/venv/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://pypi.org/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple
Obtaining file:///Users/anastasiia/Desktop/elliot
  Running command python setup.py egg_info
  running egg_info
  creating /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info
  writing /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/dependency_links.txt
  writing requirements to /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/requires.txt
  writing top-level names to /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/top_level.txt
  writing manifest file '/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/SOURCES.txt'
  reading manifest file '/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-pip-egg-info-su39l3jq/elliot.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Collecting hyperopt==0.2.5
  Using cached hyperopt-0.2.5-py2.py3-none-any.whl (965 kB)
Collecting numpy==1.18.0
  Using cached numpy-1.18.0.zip (5.4 MB)
  Running command pip subprocess to install build dependencies
  Looking in indexes: https://pypi.org/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple
  Collecting setuptools
    Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting Cython>=0.29.13
    Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
  Installing collected packages: wheel, setuptools, Cython
  Successfully installed Cython-0.29.28 setuptools-62.1.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Running from numpy source directory.
  running egg_info
  creating numpy.egg-info
  writing numpy.egg-info/PKG-INFO
  writing dependency_links to numpy.egg-info/dependency_links.txt
  writing entry points to numpy.egg-info/entry_points.txt
  writing top-level names to numpy.egg-info/top_level.txt
  writing manifest file 'numpy.egg-info/SOURCES.txt'
  package init file 'numpy/distutils/mingw/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/include/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/include/numpy/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/include/numpy/random/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/tests/data/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/npysort/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/multiarray/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/npymath/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/common/__init__.py' not found (or not a regular file)
  package init file 'numpy/core/src/umath/__init__.py' not found (or not a regular file)
  package init file 'numpy/linalg/lapack_lite/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/src/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/mixed/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/array_from_pyobj/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/kind/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/common/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/assumed_shape/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/parameter/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/string/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/size/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/tests/src/regression/__init__.py' not found (or not a regular file)
  package init file 'numpy/f2py/src/test/__init__.py' not found (or not a regular file)
  package init file 'numpy/lib/tests/data/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/include/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/_examples/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/_examples/cffi/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/_examples/cython/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/_examples/numba/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/mt19937/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/sfc64/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/pcg64/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/legacy/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/philox/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/splitmix64/__init__.py' not found (or not a regular file)
  package init file 'numpy/random/src/distributions/__init__.py' not found (or not a regular file)
  package init file 'numpy/_build_utils/src/__init__.py' not found (or not a regular file)
  reading manifest file 'numpy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'doc/build'
  no previously-included directories found matching 'doc/source/generated'
  no previously-included directories found matching 'benchmarks/env'
  no previously-included directories found matching 'benchmarks/results'
  no previously-included directories found matching 'benchmarks/html'
  no previously-included directories found matching 'benchmarks/numpy'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.swp' found anywhere in distribution
  warning: no previously-included files matching '*.bak' found anywhere in distribution
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files found matching 'LICENSES_bundled.txt'
  adding license file 'LICENSE.txt'
  writing manifest file 'numpy.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Running from numpy source directory.
  setup.py:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    run_build = parse_setuppy_commands()
  /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    required_version = LooseVersion('0.29.13')
  /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(cython_version) < required_version:
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Processing numpy/random/_bit_generator.pyx
  Processing numpy/random/_bounded_integers.pyx.in
  Processing numpy/random/_sfc64.pyx
  Processing numpy/random/_mt19937.pyx
  Processing numpy/random/mtrand.pyx
  Processing numpy/random/_generator.pyx
  Processing numpy/random/_pcg64.pyx
  Processing numpy/random/_common.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  accelerate_info:
    libraries accelerate not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
  Library accelerate was not found. Ignoring
    libraries veclib not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
  Library veclib was not found. Ignoring
    FOUND:
      extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
      extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
      define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

    FOUND:
      extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
      extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
      define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

  /bin/sh: svnversion: command not found
  non-existing path in 'numpy/distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['/Users/anastasiia/Desktop/elliot/venv/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries tatlas,tatlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries satlas,satlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries ptf77blas,ptcblas,atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries f77blas,cblas,atlas not found in /Users/anastasiia/Desktop/elliot/venv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

    FOUND:
      extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
      extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
      define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

  /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running dist_info
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.macosx-12-arm64-3.9
  creating build/src.macosx-12-arm64-3.9/numpy
  creating build/src.macosx-12-arm64-3.9/numpy/distutils
  building library "npymath" sources
  Traceback (most recent call last):
    File "/Users/anastasiia/Desktop/elliot/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/anastasiia/Desktop/elliot/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/anastasiia/Desktop/elliot/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 450, in <module>
      setup_package()
    File "setup.py", line 442, in setup_package
      setup(**metadata)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 35, in run
      egg_info.run()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/egg_info.py", line 26, in run
      self.run_command("build_src")
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/build_src.py", line 146, in run
      self.build_sources()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/build_src.py", line 157, in build_sources
      self.build_library_sources(*libname_info)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/build_src.py", line 290, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/build_src.py", line 380, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 656, in get_mathlib_info
      st = config_cmd.try_link('int main(void) { return 0;}')
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-build-env-h1wqgh2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/config.py", line 241, in try_link
      self._check_compiler()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/command/config.py", line 82, in _check_compiler
      self.fcompiler = new_fcompiler(compiler=self.fcompiler,
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/__init__.py", line 884, in new_fcompiler
      compiler = get_default_fcompiler(plat, requiref90=requiref90,
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/__init__.py", line 855, in get_default_fcompiler
      compiler_type =  _find_existing_fcompiler(matching_compiler_types,
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/__init__.py", line 806, in _find_existing_fcompiler
      c.customize(dist)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/__init__.py", line 530, in customize
      linker_so_flags = self.flag_vars.linker_so
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
      return self._get_var(name, conf_desc)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
      var = self._hook_handler(name, hook)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook
      return hook()
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/gnu.py", line 353, in get_flags_linker_so
      flags = GnuFCompiler.get_flags_linker_so(self)
    File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc/numpy/distutils/fcompiler/gnu.py", line 144, in get_flags_linker_so
      os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
    File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
      value = self.encodevalue(value)
    File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
      raise TypeError("str expected, not %s" % type(value).__name__)
  TypeError: str expected, not int
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/anastasiia/Desktop/elliot/venv/bin/python /Users/anastasiia/Desktop/elliot/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp15w8xm0b
  cwd: /private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-1_bvhw4u/numpy_94acb307542d4878a85f46abd422e4fc
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The output of my pip freeze:
```
absl-py==1.0.0
astunparse==1.6.3
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
flatbuffers==2.0
gast==0.5.3
google-auth==2.6.4
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.44.0
h5py==3.6.0
idna==3.3
importlib-metadata==4.11.3
keras==2.8.0
Keras-Preprocessing==1.1.2
libclang==13.0.0
Markdown==3.3.6
numpy==1.22.3
oauthlib==3.2.0
opt-einsum==3.3.0
protobuf==3.20.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-macos==2.8.0
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
typing_extensions==4.1.1
urllib3==1.26.9
Werkzeug==2.1.1
wrapt==1.14.0
zipp==3.8.0
```

Like I said, I would greatly appreciate any assistance. Thank you!

**Comment by albertomancino** [comment]
Hi anaklim, I had the same issue. I think it is related to the python libraries compatible with TensorFlow for Apple M1.

I suggest you:
- install your virtual environment with tensorflow-macos and tensorflow-metal ( I followed this guide -> https://developer.apple.com/metal/tensorflow-plugin/ )
- once you have activated your environment upgrade pip (pip install -U pip) and install the following libraries (pip install xxx)
    hyperopt
    scipy
    pandas
    PyYAML
    scikit_learn
    numpy
    tqdm
    Pillow
( note that there is no specification related to the library version)

- now that all the dependencies have been installed, Elliot will work. (if Elliot requires libraries not listed here, please also install them)

Here you can find my pip freeze:
absl-py==1.0.0
astunparse==1.6.3
brotlipy @ file:///Users/runner/miniforge3/conda-bld/brotlipy_1636012319596/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==5.0.0
certifi==2021.10.8
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1636046173594/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1644853463426/work
cloudpickle==2.0.0
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
conda==4.11.0
conda-package-handling @ file:///Users/runner/miniforge3/conda-bld/conda-package-handling_1636022092101/work
cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography_1639699578867/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
flatbuffers==2.0
fonttools @ file:///Users/runner/miniforge3/conda-bld/fonttools_1646922382634/work
future==0.18.2
gast==0.5.3
google-auth==2.6.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
graphviz==0.19.1
grpcio @ file:///Users/runner/miniforge3/conda-bld/grpcio_1645230392026/work
h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1637964045648/work
hyperopt==0.2.5
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1642433548627/work
importlib-metadata==4.11.2
joblib==1.1.0
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver @ file:///Users/runner/miniforge3/conda-bld/kiwisolver_1635836816114/work
libclang==13.0.0
Markdown==3.3.6
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-suite_1639359043885/work
munkres==1.1.4
natsort @ file:///home/conda/feedstock_root/build_artifacts/natsort_1643636597628/work
networkx==2.7.1
numpy==1.22.2
oauthlib==3.2.0
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pandas==1.4.1
Pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1645323199646/work
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///Users/runner/miniforge3/conda-bld/pycosat_1636020570107/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1643496850550/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1642753572664/work
PySocks @ file:///Users/runner/miniforge3/conda-bld/pysocks_1635862736740/work
pyspotlight==0.7.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz==2021.3
PyYAML==5.4.1
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1641580202195/work
requests-oauthlib==1.3.1
rsa==4.8
ruamel-yaml-conda @ file:///Users/runner/miniforge3/conda-bld/ruamel_yaml_1636009262461/work
scikit-learn==1.0.2
scipy==1.8.0
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-macos==2.8.0
tensorflow-metal==0.4.0
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
threadpoolctl==3.1.0
tornado @ file:///Users/runner/miniforge3/conda-bld/tornado_1635819711289/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1646031859244/work
typing_extensions==4.1.1
unicodedata2 @ file:///Users/runner/miniforge3/conda-bld/unicodedata2_1640031049741/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1641584929973/work
Werkzeug==2.0.3
wrapt==1.13.3
zipp==3.7.0


I wish this could help you  : )
